# ===================================================
# dbt Project Configuration
# ===================================================
# Mục đích: Định nghĩa cấu trúc và behavior của dbt project
# ===================================================

name: 'sme_pulse'
version: '1.0.0'
config-version: 2

# Profile name phải khớp với tên trong profiles.yml
profile: 'sme_pulse'

# Đường dẫn tới thư mục models
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Thư mục output
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ===== CẤU HÌNH MODELS =====
models:
  sme_pulse:
    # Staging models (trong thư mục staging/)
    staging:
      +materialized: table
      +schema: core                   # silver.core schema
      +database: silver               # silver catalog
      
    # Core models (không có models nữa)
    core:
      +materialized: table
      +schema: core                   # silver.core schema
      +database: silver               # silver catalog
      
    # Gold models (trong thư mục gold/)
    gold:
      +materialized: table
      +schema: marts                   # gold.mart schema
      +database: gold                 # gold catalog

# ===== VARIABLES =====
vars:
  # Watermark để track last processed timestamp
  start_date: '2025-01-01'
  
  # Organization filter (multi-tenant)
  default_org_id: 'org-sme-001'
