# ===================================================
# dbt Project Configuration
# ===================================================
# Mục đích: Định nghĩa cấu trúc và behavior của dbt project
# ===================================================

name: 'sme_pulse'
version: '1.0.0'
config-version: 2

# Profile name phải khớp với tên trong profiles.yml
profile: 'sme_pulse'

# Đường dẫn tới thư mục models
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Thư mục output
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ===== CẤU HÌNH MODELS =====
models:
  sme_pulse:
    staging:
      +materialized: table
      +table_format: iceberg
      +schema: core
    marts:
      +materialized: table
      +table_format: iceberg
      +schema: core

# ===== VARIABLES =====
vars:
  # Watermark để track last processed timestamp
  start_date: '2025-01-01'
  
  # Organization filter (multi-tenant)
  default_org_id: 'org-sme-001'
