# ===================================================
# dbt Profile Configuration
# ===================================================
# Mục đích: Định nghĩa cách dbt kết nối tới Postgres
# ===================================================

sme_pulse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      host: trino
      port: 8080
      catalog: silver
      schema: core
      threads: 4
      http_scheme: http
      session_properties:
        query_max_run_time: "5m"
