# ===================================================
# dbt Profile Configuration
# ===================================================
# Mục đích: Định nghĩa cách dbt kết nối tới Trino
# ===================================================

sme_pulse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none              # No authentication for local dev
      user: tuan_dev            # Tên user kết nối
      host: trino               # Trino service name in Docker network
      port: 8080                # Trino HTTP port
      database: sme_lake         # Unified Medallion catalog
      schema: bronze            # Default schema for raw sources (bronze)
      threads: 4                # Số luồng chạy song song
      http_scheme: http         # HTTP không SSL cho local dev
