# ===================================================
# dbt Profile Configuration
# ===================================================
# Mục đích: Định nghĩa cách dbt kết nối tới Postgres
# ===================================================

sme_pulse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none              # No authentication for local dev
      user: airflow             # Required field for Trino adapter
      host: trino               # Tên service trong docker-compose
      port: 8080                # Trino HTTP port (không phải 8081)
      database: iceberg         # Catalog name trong Trino
      schema: silver            # Default schema cho dbt models
      threads: 4                # Số luồng chạy song song
      http_scheme: http         # HTTP không SSL cho local dev
