# ===================================================
# dbt Profile Configuration
# ===================================================
# Mục đích: Định nghĩa cách dbt kết nối tới Trino
# ===================================================

sme_pulse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: admin
      host: trino
      port: 8080
      database: sme_pulse        # Unified catalog
      schema: silver            # default schema (bronze/silver/gold)
      threads: 4
      http_scheme: http
  target-path: /tmp/dbt_cache
  log-path: /tmp/dbt_logs