# ===================================================
# dbt Profile Configuration
# ===================================================
# Mục đích: Định nghĩa cách dbt kết nối tới Trino
# ===================================================

sme_pulse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none              # No authentication for local dev
      user: tuan_dev            # Tên user kết nối
      host: trino               # Tên service trong docker-compose
      port: 8080                # Trino HTTP port
      catalog: silver           # Catalog cho dbt models (silver catalog)
      schema: core              # Schema mặc định (silver.core)
      threads: 4                # Số luồng chạy song song
      http_scheme: http         # HTTP không SSL cho local dev
