version: 2

models:
  - name: stg_orders_vn
    description: "Silver staging - Chuẩn hóa orders với channel mapping và Việt hóa"
    tests:
      # [Test 1] Số liệu không âm (chặn lỗi nguồn)
      - dbt_utils.expression_is_true:
          expression: "qty >= 0 AND unit_cost >= 0 AND unit_price >= 0"
      # [Test 2] Key đủ để định danh dòng
      - dbt_utils.expression_is_true:
          name: stg_orders_vn_keys_not_null
          expression: "order_id_nat IS NOT NULL AND order_date IS NOT NULL"
