/*
 * ===================================================
 * Source Configuration for Raw Schema
 * ===================================================
 * Mục đích: Định nghĩa các bảng nguồn từ schema 'raw'
 * ===================================================
 */

version: 2

sources:
  - name: raw
    description: "Dữ liệu thô từ các nguồn (POS, Payments, Shipments, Bank)"
    schema: raw
    tables:
      - name: transactions_raw
        description: "Bảng lưu tất cả transactions từ các nguồn"
        columns:
          - name: event_id
            description: "ID duy nhất của event"
            tests:
              - unique
              - not_null
          
          - name: payload_json
            description: "Dữ liệu JSON gốc"
            tests:
              - not_null
          
          - name: updated_at
            description: "Thời gian cập nhật (watermark cho incremental)"
            tests:
              - not_null
