version: 2

sources:
  - name: bronze
    database: minio
    schema: default
    description: "Bronze layer on MinIO via Hive catalog"
    tables:
      - name: sales_snapshot_raw
        description: "External Parquet combined from 19 Excel files"
        external:
          location: 's3://bronze/raw/sales_snapshot/'
          options:
            format: PARQUET
