version: 2

sources:
  - name: bronze
    database: minio
    schema: default
    description: "Bronze layer - Raw external Hive tables"
    
    tables:
      - name: sales_snapshot_raw
        description: "Raw sales snapshot data from Kaggle (831K rows)"
        columns:
          - name: month
            description: "Month identifier (YYYYMM format)"
          - name: week
            description: "Week identifier"
          - name: site
            description: "Site/Store identifier"
          - name: branch_id
            description: "Branch ID"
          - name: channel_id
            description: "Channel ID (Online/Offline)"
          - name: distribution_channel
            description: "Distribution channel name"
          - name: distribution_channel_code
            description: "Distribution channel code"
          - name: sold_quantity
            description: "Quantity sold"
          - name: cost_price
            description: "Cost price"
          - name: net_price
            description: "Net selling price"
          - name: customer_id
            description: "Customer ID"
          - name: product_id
            description: "Product ID"
      
      # ===== External Data Sources =====
      - name: world_bank_indicators_raw
        description: "World Bank macro indicators (lạm phát, GDP, thất nghiệp...)"
        columns:
          - name: indicator_code
            description: "Mã chỉ số World Bank (ví dụ: FP.CPI.TOTL.ZG)"
            tests:
              - not_null
          - name: country_code
            description: "Mã quốc gia ISO (VNM = Vietnam)"
          - name: year
            description: "Năm của chỉ số"
          - name: value
            description: "Giá trị chỉ số (NULL nếu không có dữ liệu)"
          - name: ingested_at
            description: "Timestamp khi ingest data"
      
      - name: vietnam_provinces_raw
        description: "Danh sách tỉnh/thành Việt Nam (63 tỉnh) - DEPRECATED: Use seed_vietnam_locations instead"
        columns:
          - name: code
          - name: name
          - name: code_name
      
      - name: vietnam_districts_raw
        description: "Danh sách quận/huyện Việt Nam (691 quận/huyện) - DEPRECATED: Use seed_vietnam_locations instead"
        columns:
          - name: code
          - name: name
          - name: province_code
          - name: code_name
      
      # ===== Transaction Data Sources =====
      - name: bank_txn_raw
        description: "Bank transactions from CSV (105,557 rows)"
        columns:
          - name: csvbase_row_id
            description: "Original CSV row ID"
          - name: booking_id
            description: "Unique booking/transaction ID"
            tests:
              - unique
              - not_null
          - name: bookg_dt_tm_gmt
            description: "Booking datetime (GMT timestamp)"
          - name: acct_id
            description: "Account ID"
          - name: bookg_amt
            description: "Booking amount"
          - name: acct_ccy
            description: "Account currency (USD, EUR, VND...)"
          - name: bookg_cdt_dbt_ind
            description: "Credit/Debit indicator"
          - name: ctpty_nm
            description: "Counterparty name"
          - name: year_month
            description: "Year-month partition (BIGINT)"
          - name: ingested_at
            description: "Ingestion timestamp"
          - name: ingested_year_month
            description: "Ingestion year-month (VARCHAR)"
      
      - name: shipments_payments_raw
        description: "Shipments & Payments from CSV (302,010 rows) - DEPRECATED: Use stg_orders_vn instead (from sales_snapshot)"
        columns:
          - name: Transaction_ID
          - name: Customer_ID
          - name: Date
          - name: Amount
      - name: invoices_ar_raw
        description: "Raw AR Invoices data from CSV – used for DSO, overdue analysis, and payment prediction"
        meta:
          external_location: "s3a://sme-lake/bronze/raw/invoices_AR/"
          file_format: "PARQUET"
          table_type: "EXTERNAL"
        columns:
          - name: invoice_id
            description: "Unique identifier of the invoice"
          - name: doc_id
            description: "Document ID – redundant with invoice_id"
          - name: business_code
            description: "Business unit code"
          - name: cust_number
            description: "Customer number"
          - name: name_customer
            description: "Customer name (optional – free text)"
          - name: invoice_currency
            description: "Currency of the invoice"
          - name: cust_payment_terms
            description: "Customer payment terms code"
          - name: total_open_amount
            description: "Open amount on the invoice (original amount)"
          - name: isOpen
            description: "Whether invoice is still open (1) or paid (0)"
          - name: posting_id
            description: "Posting identifier (internal)"
          - name: posting_date
            description: "Date of invoice posting"
          - name: baseline_create_date
            description: "Date from which payment terms are applied"
          - name: due_in_date
            description: "Due date of the invoice"
          - name: clear_date
            description: "Date when invoice was cleared (paid)"
          - name: document_create_date
            description: "Date when document was created"
          - name: document_create_date.1
            description: "Alternative document create date (duplicate)"
          - name: document type
            description: "Type of financial document (e.g., RV)"
          - name: area_business
            description: "Business area (mostly NULL in dataset)"

  # =====================================================================
  # NEW (Phase 4): App DB Bronze Source
  # Data extracted from postgres_application_db by Airflow
  # =====================================================================
  - name: bronze_app_db
    database: minio
    schema: default
    description: "Bronze layer - App DB transactional data (OLTP → OLAP bridge)"
    
    tables:
      - name: ar_invoices_app
        description: "AR Invoices from finance.ar_invoices (Phase 3 Backend)"
        meta:
          external_location: "s3a://sme-lake/bronze/app_db/ar_invoices/"
          file_format: parquet
        columns:
          - name: id
            description: "Primary key (auto-increment)"
          - name: org_id
            description: "Organization ID (multi-tenancy)"
            tests:
              - not_null
          - name: invoice_no
            description: "Invoice number (unique per org)"
          - name: customer_id
            description: "Foreign key to core.customers"
          - name: issue_date
            description: "Invoice issue date"
          - name: due_date
            description: "Payment due date"
          - name: total_amount
            description: "Total invoice amount (VND)"
          - name: paid_amount
            description: "Amount paid (VND)"
          - name: status
            description: "Invoice status (draft/posted/paid/overdue/cancelled)"
          - name: notes
            description: "Optional notes"
          - name: created_at
            description: "Record creation timestamp"
          - name: updated_at
            description: "Record update timestamp (for incremental loading)"
      
      - name: payments_app
        description: "Payments from finance.payments (Phase 3 Backend)"
        meta:
          external_location: "s3a://sme-lake/bronze/app_db/payments/"
          file_format: parquet
        columns:
          - name: id
            description: "Primary key (auto-increment)"
          - name: org_id
            description: "Organization ID (multi-tenancy)"
            tests:
              - not_null
          - name: account_id
            description: "Foreign key to core.accounts"
          - name: transaction_date
            description: "Payment transaction date"
          - name: amount
            description: "Payment amount (VND)"
          - name: payment_method
            description: "Payment method (cash/transfer/vietqr)"
          - name: reference_code
            description: "Bank transaction reference code"
          - name: notes
            description: "Optional notes"
          - name: created_at
            description: "Record creation timestamp"
          - name: updated_at
            description: "Record update timestamp (for incremental loading)"
