version: 2

sources:
  - name: bronze
    database: minio
    schema: default
    description: "Bronze layer - Raw external Hive tables"
    
    tables:
      - name: sales_snapshot_raw
        description: "Raw sales snapshot data from Kaggle (831K rows)"
        columns:
          - name: month
            description: "Month identifier (YYYYMM format)"
          - name: week
            description: "Week identifier"
          - name: site
            description: "Site/Store identifier"
          - name: branch_id
            description: "Branch ID"
          - name: channel_id
            description: "Channel ID (Online/Offline)"
          - name: distribution_channel
            description: "Distribution channel name"
          - name: distribution_channel_code
            description: "Distribution channel code"
          - name: sold_quantity
            description: "Quantity sold"
          - name: cost_price
            description: "Cost price"
          - name: net_price
            description: "Net selling price"
          - name: customer_id
            description: "Customer ID"
          - name: product_id
            description: "Product ID"
      
      # ===== External Data Sources =====
      - name: world_bank_indicators_raw
        description: "World Bank macro indicators (lạm phát, GDP, thất nghiệp...)"
        columns:
          - name: indicator_code
            description: "Mã chỉ số World Bank (ví dụ: FP.CPI.TOTL.ZG)"
            tests:
              - not_null
          - name: country_code
            description: "Mã quốc gia ISO (VNM = Vietnam)"
          - name: year
            description: "Năm của chỉ số"
          - name: value
            description: "Giá trị chỉ số (NULL nếu không có dữ liệu)"
          - name: ingested_at
            description: "Timestamp khi ingest data"
      
      - name: vietnam_provinces_raw
        description: "Danh sách tỉnh/thành Việt Nam (63 tỉnh)"
        columns:
          - name: province_code
            description: "Mã tỉnh/thành (số)"
            tests:
              - unique
              - not_null
          - name: province_name
            description: "Tên tỉnh/thành phố"
            tests:
              - not_null
          - name: phone_code
            description: "Mã điện thoại vùng"
          - name: division_type
            description: "Loại đơn vị hành chính (Tỉnh/Thành phố)"
          - name: codename
            description: "Tên không dấu (slug)"
      
      - name: vietnam_districts_raw
        description: "Danh sách quận/huyện Việt Nam (691 quận/huyện)"
        columns:
          - name: district_code
            description: "Mã quận/huyện"
            tests:
              - unique
              - not_null
          - name: district_name
            description: "Tên quận/huyện"
          - name: province_code
            description: "Mã tỉnh/thành cha"
            tests:
              - not_null
          - name: division_type
            description: "Loại đơn vị (Quận/Huyện/Thị xã/Thành phố)"
          - name: codename
            description: "Tên không dấu (slug)"
      
      # ===== Transaction Data Sources =====
      - name: bank_txn_raw
        description: "Bank transactions from CSV (105,557 rows)"
        columns:
          - name: csvbase_row_id
            description: "Original CSV row ID"
          - name: booking_id
            description: "Unique booking/transaction ID"
            tests:
              - unique
              - not_null
          - name: bookg_dt_tm_gmt
            description: "Booking datetime (GMT timestamp)"
          - name: acct_id
            description: "Account ID"
          - name: bookg_amt
            description: "Booking amount"
          - name: acct_ccy
            description: "Account currency (USD, EUR, VND...)"
          - name: bookg_cdt_dbt_ind
            description: "Credit/Debit indicator"
          - name: ctpty_nm
            description: "Counterparty name"
          - name: year_month
            description: "Year-month partition (BIGINT)"
          - name: ingested_at
            description: "Ingestion timestamp"
          - name: ingested_year_month
            description: "Ingestion year-month (VARCHAR)"
      
      - name: shipments_payments_raw
        description: "Shipments & Payments from CSV (302,010 rows)"
        columns:
          - name: Transaction_ID
            description: "Transaction ID (DOUBLE type from CSV)"
          - name: Customer_ID
            description: "Customer ID"
          - name: Name
            description: "Customer name"
          - name: Email
            description: "Customer email"
          - name: Date
            description: "Transaction date (TIMESTAMP)"
          - name: Amount
            description: "Transaction amount"
          - name: Payment_Method
            description: "Payment method used"
          - name: Order_Status
            description: "Order status"
          - name: Shipping_Method
            description: "Shipping method"
          - name: Product_Category
            description: "Product category"
          - name: ingested_at
            description: "Ingestion timestamp"
          - name: ingested_year_month
            description: "Ingestion year-month"
