version: 2

models:
  - name: stg_transactions
    description: "Silver staging table cleaned from raw sales_snapshot."
    columns:
      - name: month_raw
        tests: [not_null]
      - name: site
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: sold_quantity
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "sold_quantity >= 0"
      - name: cost_price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "cost_price >= 0"
      - name: net_price
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "net_price >= 0"
      - name: total_revenue
        tests:
          - dbt_utils.expression_is_true:
              expression: "total_revenue = net_price * sold_quantity"
      - name: total_cost
        tests:
          - dbt_utils.expression_is_true:
              expression: "total_cost = cost_price * sold_quantity"
      - name: gross_profit
        tests:
          - dbt_utils.expression_is_true:
              expression: "gross_profit = (net_price - cost_price) * sold_quantity"

  - name: fact_sales
    description: "Gold fact table aggregated by month × site × product."
    columns:
      - name: month_key
        tests: [not_null]
      - name: site
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: qty_sold
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "qty_sold >= 0"
      - name: revenue
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "revenue >= 0"
      - name: cost
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "cost >= 0"
      - name: gross_profit
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "gross_profit = revenue - cost"
