"""Initial enterprise schema: core, finance, analytics

Revision ID: db10dff7c201
Revises: 
Create Date: 2025-11-19 02:53:19.081723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db10dff7c201'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_alerts_id'), 'alerts', ['id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_alerts_org_id'), 'alerts', ['org_id'], unique=False, schema='analytics')
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_export_jobs_id'), 'export_jobs', ['id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_export_jobs_org_id'), 'export_jobs', ['org_id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_export_jobs_status'), 'export_jobs', ['status'], unique=False, schema='analytics')
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='analytics'
    )
    op.create_index(op.f('ix_analytics_settings_id'), 'settings', ['id'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_settings_key'), 'settings', ['key'], unique=False, schema='analytics')
    op.create_index(op.f('ix_analytics_settings_org_id'), 'settings', ['org_id'], unique=False, schema='analytics')
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_accounts_id'), 'accounts', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_accounts_org_id'), 'accounts', ['org_id'], unique=False, schema='core')
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('credit_term', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_customers_id'), 'customers', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_customers_org_id'), 'customers', ['org_id'], unique=False, schema='core')
    op.create_index('ix_customers_code_org', 'customers', ['code', 'org_id'], unique=False, schema='core')
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_organizations_id'), 'organizations', ['id'], unique=False, schema='core')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_index(op.f('ix_core_roles_id'), 'roles', ['id'], unique=False, schema='core')
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('payment_term', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_suppliers_id'), 'suppliers', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_suppliers_org_id'), 'suppliers', ['org_id'], unique=False, schema='core')
    op.create_index('ix_suppliers_code_org', 'suppliers', ['code', 'org_id'], unique=False, schema='core')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_users_email'), 'users', ['email'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_id'), 'users', ['id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_users_org_id'), 'users', ['org_id'], unique=False, schema='core')
    op.create_index('ix_users_email_org', 'users', ['email', 'org_id'], unique=False, schema='core')
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='core'
    )
    op.create_index(op.f('ix_core_user_roles_org_id'), 'user_roles', ['org_id'], unique=False, schema='core')
    op.create_table('ap_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['core.suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index('ix_ap_bills_due_date_org', 'ap_bills', ['due_date', 'org_id'], unique=False, schema='finance')
    op.create_index('ix_ap_bills_status_org', 'ap_bills', ['status', 'org_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ap_bills_bill_no'), 'ap_bills', ['bill_no'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ap_bills_id'), 'ap_bills', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ap_bills_org_id'), 'ap_bills', ['org_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ap_bills_status'), 'ap_bills', ['status'], unique=False, schema='finance')
    op.create_table('ar_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['core.customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index('ix_ar_invoices_due_date_org', 'ar_invoices', ['due_date', 'org_id'], unique=False, schema='finance')
    op.create_index('ix_ar_invoices_status_org', 'ar_invoices', ['status', 'org_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ar_invoices_id'), 'ar_invoices', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ar_invoices_invoice_no'), 'ar_invoices', ['invoice_no'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ar_invoices_org_id'), 'ar_invoices', ['org_id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_ar_invoices_status'), 'ar_invoices', ['status'], unique=False, schema='finance')
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['core.accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_payments_id'), 'payments', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_payments_org_id'), 'payments', ['org_id'], unique=False, schema='finance')
    op.create_index('ix_payments_transaction_date_org', 'payments', ['transaction_date', 'org_id'], unique=False, schema='finance')
    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('ar_invoice_id', sa.Integer(), nullable=True),
    sa.Column('ap_bill_id', sa.Integer(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(ar_invoice_id IS NOT NULL AND ap_bill_id IS NULL) OR (ar_invoice_id IS NULL AND ap_bill_id IS NOT NULL)', name='check_allocation_target_exclusive'),
    sa.ForeignKeyConstraint(['ap_bill_id'], ['finance.ap_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ar_invoice_id'], ['finance.ar_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['finance.payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='finance'
    )
    op.create_index(op.f('ix_finance_payment_allocations_id'), 'payment_allocations', ['id'], unique=False, schema='finance')
    op.create_index(op.f('ix_finance_payment_allocations_org_id'), 'payment_allocations', ['org_id'], unique=False, schema='finance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_payment_allocations_org_id'), table_name='payment_allocations', schema='finance')
    op.drop_index(op.f('ix_finance_payment_allocations_id'), table_name='payment_allocations', schema='finance')
    op.drop_table('payment_allocations', schema='finance')
    op.drop_index('ix_payments_transaction_date_org', table_name='payments', schema='finance')
    op.drop_index(op.f('ix_finance_payments_org_id'), table_name='payments', schema='finance')
    op.drop_index(op.f('ix_finance_payments_id'), table_name='payments', schema='finance')
    op.drop_table('payments', schema='finance')
    op.drop_index(op.f('ix_finance_ar_invoices_status'), table_name='ar_invoices', schema='finance')
    op.drop_index(op.f('ix_finance_ar_invoices_org_id'), table_name='ar_invoices', schema='finance')
    op.drop_index(op.f('ix_finance_ar_invoices_invoice_no'), table_name='ar_invoices', schema='finance')
    op.drop_index(op.f('ix_finance_ar_invoices_id'), table_name='ar_invoices', schema='finance')
    op.drop_index('ix_ar_invoices_status_org', table_name='ar_invoices', schema='finance')
    op.drop_index('ix_ar_invoices_due_date_org', table_name='ar_invoices', schema='finance')
    op.drop_table('ar_invoices', schema='finance')
    op.drop_index(op.f('ix_finance_ap_bills_status'), table_name='ap_bills', schema='finance')
    op.drop_index(op.f('ix_finance_ap_bills_org_id'), table_name='ap_bills', schema='finance')
    op.drop_index(op.f('ix_finance_ap_bills_id'), table_name='ap_bills', schema='finance')
    op.drop_index(op.f('ix_finance_ap_bills_bill_no'), table_name='ap_bills', schema='finance')
    op.drop_index('ix_ap_bills_status_org', table_name='ap_bills', schema='finance')
    op.drop_index('ix_ap_bills_due_date_org', table_name='ap_bills', schema='finance')
    op.drop_table('ap_bills', schema='finance')
    op.drop_index(op.f('ix_core_user_roles_org_id'), table_name='user_roles', schema='core')
    op.drop_table('user_roles', schema='core')
    op.drop_index('ix_users_email_org', table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_org_id'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_id'), table_name='users', schema='core')
    op.drop_index(op.f('ix_core_users_email'), table_name='users', schema='core')
    op.drop_table('users', schema='core')
    op.drop_index('ix_suppliers_code_org', table_name='suppliers', schema='core')
    op.drop_index(op.f('ix_core_suppliers_org_id'), table_name='suppliers', schema='core')
    op.drop_index(op.f('ix_core_suppliers_id'), table_name='suppliers', schema='core')
    op.drop_table('suppliers', schema='core')
    op.drop_index(op.f('ix_core_roles_id'), table_name='roles', schema='core')
    op.drop_table('roles', schema='core')
    op.drop_index(op.f('ix_core_organizations_id'), table_name='organizations', schema='core')
    op.drop_table('organizations', schema='core')
    op.drop_index('ix_customers_code_org', table_name='customers', schema='core')
    op.drop_index(op.f('ix_core_customers_org_id'), table_name='customers', schema='core')
    op.drop_index(op.f('ix_core_customers_id'), table_name='customers', schema='core')
    op.drop_table('customers', schema='core')
    op.drop_index(op.f('ix_core_accounts_org_id'), table_name='accounts', schema='core')
    op.drop_index(op.f('ix_core_accounts_id'), table_name='accounts', schema='core')
    op.drop_table('accounts', schema='core')
    op.drop_index(op.f('ix_analytics_settings_org_id'), table_name='settings', schema='analytics')
    op.drop_index(op.f('ix_analytics_settings_key'), table_name='settings', schema='analytics')
    op.drop_index(op.f('ix_analytics_settings_id'), table_name='settings', schema='analytics')
    op.drop_table('settings', schema='analytics')
    op.drop_index(op.f('ix_analytics_export_jobs_status'), table_name='export_jobs', schema='analytics')
    op.drop_index(op.f('ix_analytics_export_jobs_org_id'), table_name='export_jobs', schema='analytics')
    op.drop_index(op.f('ix_analytics_export_jobs_id'), table_name='export_jobs', schema='analytics')
    op.drop_table('export_jobs', schema='analytics')
    op.drop_index(op.f('ix_analytics_alerts_org_id'), table_name='alerts', schema='analytics')
    op.drop_index(op.f('ix_analytics_alerts_id'), table_name='alerts', schema='analytics')
    op.drop_table('alerts', schema='analytics')
    # ### end Alembic commands ###
